// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanLH4iDliwS7L8F6eB7AdjO_KAM8rN6I',
    appId: '1:110174417153:web:64db3dfa339bb70df42b00',
    messagingSenderId: '110174417153',
    projectId: 'ai-learning-tracker-97e11',
    authDomain: 'ai-learning-tracker-97e11.firebaseapp.com',
    databaseURL: 'https://ai-learning-tracker-97e11-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-learning-tracker-97e11.firebasestorage.app',
    measurementId: 'G-SMPVQXCLQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgOrR7XKT_h2CYN38ZjpjiD8xEIE2iMQ',
    appId: '1:110174417153:android:425946e0d843450df42b00',
    messagingSenderId: '110174417153',
    projectId: 'ai-learning-tracker-97e11',
    databaseURL: 'https://ai-learning-tracker-97e11-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-learning-tracker-97e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamsxcK41v_D6WaBqobP0oDMdNyIR6iEE',
    appId: '1:110174417153:ios:161c2fb43af71e72f42b00',
    messagingSenderId: '110174417153',
    projectId: 'ai-learning-tracker-97e11',
    storageBucket: 'ai-learning-tracker-97e11.firebasestorage.app',
    iosBundleId: 'com.example.aiLearningTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDamsxcK41v_D6WaBqobP0oDMdNyIR6iEE',
    appId: '1:110174417153:ios:161c2fb43af71e72f42b00',
    messagingSenderId: '110174417153',
    projectId: 'ai-learning-tracker-97e11',
    storageBucket: 'ai-learning-tracker-97e11.firebasestorage.app',
    iosBundleId: 'com.example.aiLearningTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCanLH4iDliwS7L8F6eB7AdjO_KAM8rN6I',
    appId: '1:110174417153:web:469b904d4712ecb5f42b00',
    messagingSenderId: '110174417153',
    projectId: 'ai-learning-tracker-97e11',
    authDomain: 'ai-learning-tracker-97e11.firebaseapp.com',
    storageBucket: 'ai-learning-tracker-97e11.firebasestorage.app',
    measurementId: 'G-R7ZG2KNMDW',
  );
}